config/routes.rb
Rails.application.routes.draw do

  root 'orders#index'

  get  'storage'  => 'ingredients#index'

  post 'orders/check_storage' 

  resources :cookie_orders
  resources :cookies
  resources :ingredients
  resources :recipes
  resources :pallets do
    put 'block', on: :collection
    put 'unblock', on: :collection
  end
  resources :orders
  

  # resources :relationships,       only: [:create, :destroy]

end

app/models/cookie.rb
class Cookie < ActiveRecord::Base
	has_many :recipes
	has_many :pallets
	has_many :cookie_orders

	
	validates_presence_of :name


	def build_recipe(ingredient, amount)
	  recipes.build(ingredient_id: ingredient.id, quantity: amount).save
	end


	def sufficient?
		@recipes = Recipe.where(cookie_id: id)
		@recipes.each do | o | 
			return false if o.quantity > Ingredient.find_by(id: o.ingredient_id).quantity
		end

		@recipes.each do | o |
			i = Ingredient.find_by(id: o.ingredient_id)
			i.update(quantity: i.quantity - o.quantity)
		end

		return true

	end





	private 

	#	def downcase_name
	#		name.downcase!
	#	end


end

app/models/cookie_order.rb
class CookieOrder < ActiveRecord::Base
	belongs_to :cookies
	belongs_to :orders

	validates_presence_of :amount, :order_id, :cookie_id
	validates :amount, :numericality => { :greater_than_or_equal_to => 0 }
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders
	
	validates_presence_of :name, :adress
	
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	has_many :recipes

	validates_presence_of :name, :amount_delivered, :quantity
	validates :amount_delivered, :numericality => { :greater_than_or_equal_to => 0 }
	before_save :update_quantity_after_restock, if: :amount_delivered_changed?




	private 

		def update_quantity_after_restock
			self.quantity = quantity + amount_delivered
		end




end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :customer
	has_many :cookie_orders
	has_many :pallets

	validates_presence_of :requested_delivery_date, :customer_id


end

app/models/pallet.rb
class Pallet < ActiveRecord::Base
	belongs_to :order
	belongs_to :cookie

	validates_presence_of :order_id, :cookie_id



end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :ingredient
	belongs_to :cookie
	validates_presence_of :quantity, :ingredient_id, :cookie_id
	validates :quantity, :numericality => { :greater_than_or_equal_to => 0 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cookie_orders_controller.rb
class CookieOrdersController < ApplicationController

	def new
		@cookie_order = CookieOrder.new
		@cookies = Cookie.all
		@order_id = params[:order_id]
	end

	def create
  	@cookie_order = CookieOrder.new(order_params)
  	if @cookie_order.save
      	flash[:notice] = "Cookie added"
      	redirect_to order_url(@cookie_order.order_id)
 		else
        flash[:info] = "Bad amount, try again"
    		redirect_to order_url(@cookie_order.order_id)
 		end
  end

  	private 
  	  def order_params
    	  params.require(:cookie_order).permit(:amount, :cookie_id, :order_id)
      end

end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController

  def index
    @cookies = Cookie.all
  end

  def show
  	@cookie = Cookie.find(params[:id])
  	@cookie_recipe = Recipe.where(cookie_id: @cookie)
  	@ingredients = Ingredient.all
  end
	
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	before_action :set_ingredient, only: [:update]


	def index
		@ingredients = Ingredient.order(:name)
	end

	def update
		amount = ingredient_params[:amount_delivered]
		if @ingredient.update(amount_delivered: amount)
			flash[:info] = "#{@ingredient.name} restocked with #{amount} units"
	  	else
	  		flash[:info] = "Bad amount"
		end
		redirect_to :back
	end

	# CALLBACK!

	# Turbolinks


	private 

	def ingredient_params
		params.require(:ingredient).permit(:name, :amount_delivered)
	end

	def set_ingredient
		@ingredient = Ingredient.find(params[:id])
	end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :set_order, only: [:show, :edit, :update, :destroy]

	def index


    if params[:search].nil?
		  @orders = Order.all.order(:requested_delivery_date)
    else
      search_orders
    end

  end

	def new
		@order = Order.new
	end

	def create
    	@order = Order.new(order_params, order_id: params[:order_id])
    	if @order.save
        	flash[:info] = "Order initialized"
        redirect_to order_url(@order)
   		else
      		render 'new'
   		end
  	end

  	def show
      @cookie_orders = CookieOrder.where(order_id: params[:id])
      @cookies = Cookie.all
      @pallets = Pallet.where(order_id: params[:id])
    end

    def check_storage
      c_id = params[:cookie_id]
      o_id = params[:order_id]
      cookie = Cookie.find_by(id: c_id)
      if Pallet.where(order_id: o_id, cookie_id: c_id).size < params[:amount].to_i
        if cookie.sufficient?
          pallet = Pallet.create(cookie_id: c_id, order_id: o_id)
          flash[:info] = "Pallet produced, storage updated"
        else 
         flash[:info] = "Not enough resources, please restock storage"
        end
      else
         flash[:info] = "Order already fulfilled"
       end

    redirect_to :back
    end


    def edit
    end

    def update
    end

    def destroy
    end






	private
    def order_params
    	params.require(:order).permit(:requested_delivery_date, :delivered_date, :customer_id)
    end

    def set_order
      @order = Order.find(params[:id])
    end



  def search_orders
      from = params[:search][:from_date]
      from = Date.new(2010) if from.blank?
      to = params[:search][:to_date]
      to = Date.new(2100)   if to.blank?
      @orders = Order.where(requested_delivery_date: from.to_date..to.to_date)
      flash[:info] = "Showing orders from #{from} to #{to}, total #{@orders.size}"
  end

end

app/controllers/pallets_controller.rb
class PalletsController < ApplicationController

	def index
		if params[:search].nil?
			@pallets_ok = Pallet.where(blocked: false).sort_by { |p| p.created_at }.reverse
			@pallets_blocked = Pallet.where(blocked: true).sort_by { |p| p.created_at }.reverse
		else
			search_pallets
		end
	end


	def block
		Pallet.where(:id => params[:pallet_ids]).update_all(blocked: true)
		redirect_to :back
	end

	def unblock
		Pallet.where(:id => params[:pallet_ids]).update_all(blocked: false)
		redirect_to :back
	end


	private

	def pallet_params
    	params.require(:pallet).permit(:cookie_id, :order_id)
    end


	def search_pallets
		pallets = Pallet.all
		pallets = pallets.where(cookie_id: params[:search][:cookie_id]) if params[:search][:cookie_id].present?
	    from = params[:search][:from_date]
	    from = Date.new(2010) if from.blank?
	    to = params[:search][:to_date]
	    to = Date.new(2100)   if to.blank?
	    pallets = pallets.where(created_at: from.to_date..to.to_date)
	    @pallets_ok = pallets.where(blocked: false).sort_by { |p| p.created_at }.reverse
	    @pallets_blocked = pallets.where(blocked: true).sort_by { |p| p.created_at }.reverse
	    flash[:info] = "Showing pallets from #{from} to #{to}, total #{pallets.size}"
  end


end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookie_orders_helper.rb
module CookieOrdersHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pallets_helper.rb
module PalletsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/cookie_orders/new.html.erb
<% provide(:title, 'Add cookie') %>
<h1>Specify order</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@cookie_order) do |f| %>
    
    <%= f.label :cookie %>
    <%= f.collection_select :cookie_id, Cookie.all, :id, :name, class: 'form-control' %>
    <br>
    <%= f.label :pallets%>
    <%= f.number_field :amount, class: 'form-control' %>

    <%= f.hidden_field :order_id, value: @order_id %>

    <br>
    <%= f.submit "Complete cookie order", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/ingredients/index.html.erb
<% provide(:title, 'Storage') %>


<h1>All ingredients in store</h1>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th>Last Delivery</th>
      <th>Amount Delivered</th>
      <th>New order</th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |i| %>
      <tr>
        <%= form_for(i, layout: :horizontal) do |f| %>
        <td><%= i.name %></td>
        <td><%= i.quantity %></td>
        <td><%= i.updated_at.to_date %></td>
        <td><%= i.amount_delivered %></td>
        <td><%= f.number_field :amount_delivered, value: 0, class: 'form-control' %></td>
        <td><%= f.submit "Restock", class: "btn btn-primary" %></td>
        <% end %>

        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/index.html.erb
<% provide(:title, 'All orders') %>

<h1>Orders</h1>
<p>

<%= form_tag orders_path, :method => 'get' do %>

<%= label_tag :from_date %>
<%= date_field(:search, :from_date) %>

<%= label_tag :to_date %>
<%= date_field(:search, :to_date)%>

<%= submit_tag "Search" %>
<% end %>
 	
 	<h3>Active orders</h3>

 	<table class="table table-striped">
  <thead>
    <tr>
      <th>Order number</th>
      <th>Customer</th>
      <th>Adress</th>
      <th>Requested delivery</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |o| %>
      <tr>
        <td><%= o.id %></td>
        <% customer = Customer.find(o.customer_id) %>
        <td><%= customer.name %></td>
        <td><%= customer.adress %></td>
        <td><%= o.requested_delivery_date %></td>
        <td><%= link_to 'Show', o %></td>
      </tr>
    <% end %>
  </tbody>
</table>


 	<li><%= link_to "Place order", new_order_path %></li>


</p>

app/views/orders/new.html.erb
<% provide(:title, 'Begin order') %>
<h1>Begin order</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@order) do |f| %>
    
    <%= f.label :customer %>
    <%= f.collection_select :customer_id, Customer.all, :id, :name, class: 'form-control' %>
    <br>
    <%= f.label :requested_delivery_date %>
    <%= f.date_field :requested_delivery_date, class: 'form-control' %>


    <%= f.submit "Continue order", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<% provide(:title, 'Order details') %>

<h1>Listing Order</h1>

<h2>Order number: <%= @order.id %></h2>

<h3> To be delivered:  <%= @order.requested_delivery_date %></h3>

<% if !@cookie_orders.nil? %>
  <table class="table table-striped">
   <thead>
      <tr>
      </tr>
      <tr>
        <th> Name </th>
        <th> Ordered </th>
         <th> Produced </th>
      </tr>
    </thead>

    <tbody>
      <% @cookie_orders.each do |o| %>
      <tr>
        <td><%= (@cookies.find_by id: o.cookie_id).name %></td>
        <td><%= o.amount %></td>
        <td><%= Pallet.where(cookie_id: o.cookie_id, order_id: @order.id).size %></td>
        <td><%= button_to 'Produce', orders_check_storage_path(:amount => o.amount, :cookie_id => o.cookie_id, :order_id => @order.id), method: :post %></td>
        
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<br>

<li><%= link_to "New cookie order", new_cookie_order_path(order_id: @order.id) %></li>

app/views/pallets/index.html.erb
<% provide(:title, 'All pallets') %>

<h1>Pallets</h1>

<%= form_tag pallets_path, :method => 'get' do %>

<%= collection_select(:search, :cookie_id, Cookie.all, :id, :name, {include_blank: true, value: ""}, class: "select2") %>


<%= label_tag :from_date %>
<%= date_field(:search, :from_date) %>

<%= label_tag :to_date %>
<%= date_field(:search, :to_date)%>

<%= submit_tag "Search" %>
<% end %>

<%= @current_search %>

<%= form_tag block_pallets_path, :method => :put do %>
<p>  
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Select</th>
        <th>Pallet number</th>
        <th>Order ID</th>
        <th>Product</th>
        <th>Location</th>
        <th>Production date</th>
      </tr>
    </thead>
    <tbody>
      
      <% @pallets_ok.each do |o| %>
      <tr>
        <td> <%= check_box_tag "pallet_ids[]", o.id %></td>
        <td><%= o.id %></td>
        <td><%= o.order_id %></td>
        <td><%= Cookie.find_by(id: o.cookie_id).name %></td>
        <td><%= o.location %></td>
        <td><%= o.created_at.to_date %></td> 
      </tr>
      <% end %>
    </tbody>
    <td>
    </td>
  </table>
</p>
<%= submit_tag "Block selected" %>
<% end %>



<h1> Blocked pallets</h1>
<%= form_tag unblock_pallets_path, :method => :put do %>
<p>  
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Select</th>
        <th>Pallet number</th>
        <th>Order ID</th>
        <th>Product</th>
        <th>Location</th>
        <th>Production date</th>
      </tr>
    </thead>
    <tbody>
      <% @pallets_blocked.each do |o| %>
      <tr>
        <td> <%= check_box_tag "pallet_ids[]", o.id %></td>
        <td><%= o.id %></td>
        <td><%= o.order_id %></td>
        <td><%= Cookie.find_by(id: o.cookie_id).name %></td>
        <td><%= o.location %></td>
        <td><%= o.created_at.to_date %></td> 
      </tr>
      <% end %>
    </tbody>
  </table>
</p>
<td><%= submit_tag "Unblock selected" %></td>
<% end %>

app/views/pallets/new.html.erb
<% provide(:title, 'Add cookie') %>
<h1>Specify order</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@pallet) do |f| %>
    
    <%= f.label :cookie %>
    <%= f.collection_select :cookie_id, Cookie.all, :id, :name, class: 'form-control' %>

    <%= f.label :order %>
    <%= f.number_field :order_id, class: 'form-control' %>


    <%= f.submit "Complete cookie order", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>